# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 544)
        MainWindow.setStyleSheet("background-color: rgb(34, 34, 34);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setStyleSheet("background-color: rgb(24, 24, 24);")
        self.header.setObjectName("header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.menu = QtWidgets.QPushButton(self.frame)
        self.menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("🦆 icon _Bars_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu.setIcon(icon)
        self.menu.setIconSize(QtCore.QSize(30, 30))
        self.menu.setObjectName("menu")
        self.horizontalLayout_3.addWidget(self.menu)
        self.title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(9)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 25pt \"MS Shell Dlg 2\";\n"
"padding-bottom: 2px;")
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.frame_2 = QtWidgets.QFrame(self.header)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.notification = QtWidgets.QPushButton(self.frame_2)
        self.notification.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("🦆 icon _bell_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notification.setIcon(icon1)
        self.notification.setIconSize(QtCore.QSize(30, 30))
        self.notification.setObjectName("notification")
        self.horizontalLayout_2.addWidget(self.notification)
        self.account = QtWidgets.QPushButton(self.frame_2)
        self.account.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("🦆 icon _User Circle_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.account.setIcon(icon2)
        self.account.setIconSize(QtCore.QSize(40, 40))
        self.account.setObjectName("account")
        self.horizontalLayout_2.addWidget(self.account)
        self.horizontalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.header, 0, QtCore.Qt.AlignTop)
        self.main = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main.sizePolicy().hasHeightForWidth())
        self.main.setSizePolicy(sizePolicy)
        self.main.setObjectName("main")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.main)
        self.horizontalLayout_4.setContentsMargins(0, 7, 0, 0)
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_menu = QtWidgets.QWidget(self.main)
        self.left_menu.setMinimumSize(QtCore.QSize(300, 0))
        self.left_menu.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"border: none;\n"
"border-radius: 25;")
        self.left_menu.setObjectName("left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.left_menu)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Consolas\";\n"
"background-color: rgb(50, 162, 244);\n"
"border: none;\n"
"border-radius: 30;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Consolas\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Consolas\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Consolas\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Consolas\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 20pt \"Consolas\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_5.addWidget(self.pushButton_2)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_3.addWidget(self.widget)
        self.horizontalLayout_4.addWidget(self.left_menu)
        self.main_bar = QtWidgets.QWidget(self.main)
        self.main_bar.setStyleSheet("background-color: rgb(24, 24, 24);\n"
"border: none;\n"
"border-radius: 25;")
        self.main_bar.setObjectName("main_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_bar)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_bar)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.main_bar)
        self.verticalLayout.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "EV Charge"))
        self.pushButton_3.setText(_translate("MainWindow", "Home"))
        self.pushButton_4.setText(_translate("MainWindow", "Stations"))
        self.pushButton_5.setText(_translate("MainWindow", "Report"))
        self.pushButton_6.setText(_translate("MainWindow", "Security"))
        self.pushButton.setText(_translate("MainWindow", "Settings"))
        self.pushButton_2.setText(_translate("MainWindow", "About"))
# import account_rc
# import menu_rc
# import noti_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
